4.-MVC/MVCEF3Capas/Presentacion/Controllers/AlumnosController.cs
using Entidades;
using Negocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentacion.Controllers
{
    public class AlumnosController : Controller
    {
        private NAlumno objCRUDAlu = new NAlumno();
        private NEstado objCRUDEstado = new NEstado();
        private NEstatus objCRUDEstatus = new NEstatus();

        // GET: Alumnos
        public ActionResult Index()
        {
            return View(objCRUDAlu.NConsultar());
        }

        // GET: Alumnos/Details/5
        public ActionResult Details(int idAlumno)
        {
            return View(objCRUDAlu.NConsultar(idAlumno));
        }

        // GET: Alumnos/Create
        public ActionResult Create()
        {
            ViewBag.idEstado = new SelectList(objCRUDEstado.NConsultar(), "id", "nombre");
            ViewBag.idEstatus = new SelectList(objCRUDEstatus.NConsultar(), "id", "nombre");
            return View();
        }

        // POST: Alumnos/Create
        [HttpPost]
        public ActionResult Create(Alumnos alumno)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // TODO: Add insert logic here
                    objCRUDAlu.NAgregar(alumno);
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }
            else
            {
                ViewBag.idEstado = new SelectList(objCRUDEstado.NConsultar(), "id", "nombre");
                ViewBag.idEstatus = new SelectList(objCRUDEstatus.NConsultar(), "id", "nombre");
                return View(alumno);
            }
  

        }

        // GET: Alumnos/Edit/5
        public ActionResult Edit(int idAlumno)
        {
            Alumnos unAlumno = objCRUDAlu.NConsultar(idAlumno);
            ViewBag.idEstado = new SelectList(objCRUDEstado.NConsultar(), "id", "nombre", unAlumno.idEstadoOrigen);
            ViewBag.idEstatus = new SelectList(objCRUDEstatus.NConsultar(), "id", "nombre", unAlumno.idEstatus);
            return View(unAlumno);
        }

        // POST: Alumnos/Edit/5
        [HttpPost]
        public ActionResult Edit(int idAlumno, Alumnos unAlumno)
        {
           
            if (ModelState.IsValid)
            {
                try
                {
                    // TODO: Add update logic here
                    objCRUDAlu.NActualizar(unAlumno);
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }
            else
            {
                ViewBag.idEstado = new SelectList(objCRUDEstado.NConsultar(), "id", "nombre");
                ViewBag.idEstatus = new SelectList(objCRUDEstatus.NConsultar(), "id", "nombre");
                return View(unAlumno);
            }

        }

        // GET: Alumnos/Delete/5
        public ActionResult Delete(int idAlumno)
        {
            return View(objCRUDAlu.NConsultar(idAlumno));
        }

        // POST: Alumnos/Delete/5
        [HttpPost]
        public ActionResult Delete(int idAlumno, Alumnos alumno)
        {
            try
            {
                // TODO: Add delete logic here
                objCRUDAlu.NEliminar(idAlumno);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult _AportacionesIMSS(int id)
        {
            return PartialView(objCRUDAlu.CalcularIMSS(id));
        }

        public ActionResult _TablaISR(int id)
        {
            return PartialView(objCRUDAlu.CalcularISR(id));
        }


        public ActionResult Regresar()
        {
           // objCRUDAlu.CalcularIMSS(19);
            //objCRUDAlu.CalcularISR(19);

            return RedirectToAction("Index");
        }
    }
}

4.-MVC/MVCEF3Capas/Presentacion/Controllers/EstatusAlumnosController.cs
using Entidades;
using Negocio;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentacion.Controllers
{
    public class EstatusAlumnosController : Controller
    {

        NEstatusAlumnos objCRUD = new NEstatusAlumnos();  
        // GET: EstatusAlumnos
        public ActionResult Index()
        {
            return View(objCRUD.WAPINConsultar());
        }

        // GET: EstatusAlumnos/Details/5
        public ActionResult Details(int id)
        {
            return View(objCRUD.WAPINConsultar(id));
        }

        // GET: EstatusAlumnos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EstatusAlumnos/Create
        [HttpPost]
        public ActionResult Create(EstatusAlumnos unEstatus)
        {
            try
            {
                // TODO: Add insert logic here

                unEstatus = objCRUD.WAPINAgregar(unEstatus);

                return View("Details", unEstatus);
            }
            catch
            {
                return View();
            }
        }

        // GET: EstatusAlumnos/Edit/5
        public ActionResult Edit(int id)
        {
            return View(objCRUD.WAPINConsultar(id));
        }

        // POST: EstatusAlumnos/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, EstatusAlumnos unEstatus)
        {
            try
            {
                // TODO: Add update logic here
                objCRUD.WAPINActualizar(unEstatus);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: EstatusAlumnos/Delete/5
        public ActionResult Delete(int id)
        {
            return View(objCRUD.WAPINConsultar(id));
        }

        // POST: EstatusAlumnos/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                objCRUD.WAPINEliminar(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

4.-MVC/MVCEF3Capas/Presentacion/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentacion2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

4.-MVC/MVCEF3Capas/Presentacion/Views/Alumnos/Create.cshtml
@model Entidades.Alumnos

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Agregar un Alumno</h2>


@using (Html.BeginForm())
{


    <div class="form-group row">
        @Html.Label("Nombre", htmlAttributes: new { @class = "col-sm-3 col-form-label text-right" })
        <div class="col-sm-9">
            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group row">
        @Html.Label("Primer Apellido", htmlAttributes: new { @class = "col-sm-3 col-form-label text-right" })
        <div class="col-sm-9">
            @Html.EditorFor(model => model.primerApellido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.primerApellido, "", new { @class = "text-danger" })


        </div>
    </div>
    <div class="form-group row">
        @Html.Label("Segundo Apellido", htmlAttributes: new { @class = "col-sm-3 col-form-label text-right" })
        <div class="col-sm-9">
            @Html.EditorFor(model => model.segundoApellido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.segundoApellido, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group row">
        @Html.Label("Fecha de Nacimiento", htmlAttributes: new { @class = "col-sm-3 col-form-label text-right" })
        <div class="col-sm-9">
            @Html.EditorFor(model => model.fechaNacimiento, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.fechaNacimiento, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group row">
        @Html.Label("CURP", htmlAttributes: new { @class = "col-sm-3 col-form-label text-right" })
        <div class="col-sm-9">
            @Html.EditorFor(model => model.curp, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.curp, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group row">
        @Html.Label("Correo", htmlAttributes: new { @class = "col-sm-3 col-form-label text-right" })
        <div class="col-sm-9">
            @Html.EditorFor(model => model.correo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.correo, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group row">
        @Html.Label("Telefono", htmlAttributes: new { @class = "col-sm-3 col-form-label text-right" })
        <div class="col-sm-9">
            @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group row">
        @Html.Label("Sueldo", htmlAttributes: new { @class = "col-sm-3 col-form-label text-right" })
        <div class="col-sm-9">
            @Html.EditorFor(model => model.sueldo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.sueldo, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group row">
        @Html.Label("Estado", htmlAttributes: new { @class = "col-sm-3 col-form-label text-right" })
        <div class="col-sm-9">
            @Html.DropDownList("idEstadoOrigen", (SelectList)ViewBag.idEstado, htmlAttributes: new { @class = "form-control" })
            @*@Html.EditorFor(model => model.idEstadoOrigen, new { htmlAttributes = new { @class = "col-sm-3 col-form-label text-right" } })*@
        </div>
    </div>
    <div class="form-group row">
        @Html.Label("Estatus", htmlAttributes: new { @class = "col-sm-3 col-form-label text-right" })
        <div class="col-sm-9">
            @Html.DropDownList("idEstatus", (SelectList)ViewBag.idEstatus, htmlAttributes: new { @class = "form-control" })

            @*@Html.EditorFor(model => model.idEstadoOrigen, new { htmlAttributes = new { @class = "col-sm-3 col-form-label text-right" } })*@
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-12 text-start">
            <br />
            <input type="Submit" value="Guardar" class="btn btn-primary btn-sm" />
        </div>
    </div>
}
<br />
@Html.ActionLink("Regresar al Index", "Regresar", "Alumnos", htmlAttributes: new { @class = "btn btn-grey btn-sm" })

4.-MVC/MVCEF3Capas/Presentacion/Views/Alumnos/Delete.cshtml
@model Entidades.Alumnos

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar Alumno</h2>
<h3>¿Esta seguro que desea eliminar al alumno? </h3>

    @using (Html.BeginForm())
    {
        <table border="0" style="border-collapse: separate; border-spacing: 10px; width: 50%;">
            <tr>
                <th style="text-align: right;">ID</th>
                <td>
                    @Html.DisplayFor(m => m.id)
                </td>
            </tr>
            <tr>
                <th style="text-align: right;">Nombre</th>
                <td>
                    @Html.DisplayFor(m => m.nombre)
                </td>
            </tr>
            <tr>
                <th style="text-align: right;">Primer Apellido</th>
                <td>
                    @Html.DisplayFor(m => m.primerApellido)
                </td>
            </tr>
            <tr>
                <th style="text-align: right;">Segundo Apellido</th>
                <td>
                    @Html.DisplayFor(m => m.segundoApellido)
                </td>
            </tr>
            <tr>
                <th style="text-align: right;">Fecha de Nacimiento</th>
                <td>
                    @*@Html.DisplayFor(m => m.fechaNacimiento.ToString("yyyy-MM-dd"))*@

                    @{
                        string Fec = Model.fechaNacimiento.ToString("yyyy-MM-dd");

                        @Html.DisplayFor(m => Fec);
                    }
                </td>
            </tr>
            <tr>
                <th style="text-align: right;">CURP</th>
                <td>
                    @Html.DisplayFor(m => m.curp)
                </td>
            </tr>
            <tr>
                <th style="text-align: right;">Correo</th>
                <td>
                    @Html.DisplayFor(m => m.correo)
                </td>
            </tr>
            <tr>
                <th style="text-align: right;">Teléfono</th>
                <td>
                    @Html.DisplayFor(m => m.telefono)
                </td>
            </tr>
            <tr>
                <th style="text-align: right;">Sueldo Mensual</th>
                <td>
                    @Html.DisplayFor(m => m.sueldo)
                </td>
            </tr>
            <tr>
                <th style="text-align: right;">Estado</th>
                <td>
                    @Html.DisplayFor(m => m.Estados.nombre)
                </td>
            </tr>
            <tr>
                <th style="text-align: right;">Estatus</th>
                <td>
                    @Html.DisplayFor(m => m.EstatusAlumnos.Nombre)
                </td>
            </tr>
        </table>

        <div>
            @*@Html.ActionLink("Eliminar", "Eliminar", "Alumnos", new { idAlumno = @Model.id }, htmlAttributes: new { @class = "btn btn-danger btn-sm" })*@
            <br />
            <input type="Submit" value="Eliminar" class="btn btn-danger" />

        </div>

    }

    <br />
    @Html.ActionLink("Regresar al Index", "Regresar", "Alumnos", htmlAttributes: new { @class = "btn btn-grey btn-sm" })

4.-MVC/MVCEF3Capas/Presentacion/Views/Alumnos/Details.cshtml
@model Entidades.Alumnos

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Detalles del Alumno</h2>


<table border="0" style="border-collapse: separate; border-spacing: 10px; width: 50%;">
    <tr>
        <th style="text-align: right;">ID</th>
        <td>
            @Html.DisplayFor(m => m.id)
        </td>
    </tr>
    <tr>
        <th style="text-align: right;">Nombre</th>
        <td>
            @Html.DisplayFor(m => m.nombre)
        </td>
    </tr>
    <tr>
        <th style="text-align: right;">Primer Apellido</th>
        <td>
            @Html.DisplayFor(m => m.primerApellido)
        </td>
    </tr>
    <tr>
        <th style="text-align: right;">Segundo Apellido</th>
        <td>
            @Html.DisplayFor(m => m.segundoApellido)
        </td>
    </tr>
    <tr>
        <th style="text-align: right;">Fecha de Nacimiento</th>
        <td>
            @{
                string Fec = Model.fechaNacimiento.ToString("yyyy-MM-dd");

                @Html.DisplayFor(m => Fec);
            }
        </td>
    </tr>
    <tr>
        <th style="text-align: right;">CURP</th>
        <td>
            @Html.DisplayFor(m => m.curp)
        </td>
    </tr>
    <tr>
        <th style="text-align: right;">Correo</th>
        <td>
            @Html.DisplayFor(m => m.correo)
        </td>
    </tr>
    <tr>
        <th style="text-align: right;">Teléfono</th>
        <td>
            @Html.DisplayFor(m => m.telefono)
        </td>
    </tr>
    <tr>
        <th style="text-align: right;">Sueldo Mensual</th>
        <td>
            @Html.DisplayFor(m => m.sueldo)
        </td>
    </tr>
    <tr>
        <th style="text-align: right;">Estado</th>
        <td>
            @Html.DisplayFor(m => m.Estados.nombre)
        </td>
    </tr>
    <tr>
        <th style="text-align: right;">Estatus</th>
        <td>
            @Html.DisplayFor(m => m.EstatusAlumnos.Nombre)
        </td>
    </tr>
</table>

<div>
    <input id="BtnIMSS" type="button" value="CalcularIMSS" class="btn btn-outline-info btn-sm" onclick="CalcularIMSSjs(@Model.id)" />

</div>
<br />
<div>
    <input id="btnISR" type="button" value="CalcularISR" class="btn btn-outline-success  btn-sm" onclick="CalcularISRjs(@Model.id)" />

</div>

<br />
@Html.ActionLink("Regresar al Index", "Regresar", "Alumnos", htmlAttributes: new { @class = "btn btn-grey btn-sm" })



<!-- Modal -->
<div class="modal fade" id="ModalDetails" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="cuerpoModal">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    function CalcularIMSSjs(id) {
        $('exampleModalLabel').text("Aportaciones IMSS");
        let url = "@Url.Action("_AportacionesIMSS","Alumnos")" + "/" + id
        AjaxGEThtmlIMSS(url, MostrarModal);
    }

    function CalcularISRjs(id) {
     $('exampleModalLabel').text("Calcular ISR");
     let url = "@Url.Action("_TablaISR", "Alumnos")" + "/" + id
     AjaxGEThtmlIMSS(url, MostrarModal);
 }


    function MostrarModal(html) {
        $('#cuerpoModal').html(html);
        $('#ModalDetails').modal('show');
    }


</script>

4.-MVC/MVCEF3Capas/Presentacion/Views/Alumnos/Edit.cshtml
@model Entidades.Alumnos

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Editar un Alumno</h2>

@using (Html.BeginForm())
{

    <div class="form-group row">
        @Html.LabelFor(m => m.id, htmlAttributes: new { @class = "col-sm-3 col-form-label text-left" })
        <div class="col-sm-9">
            @Html.HiddenFor(model => model.id)

            @*@Html.DisplayFor(m => m.id)*@
            @*@Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control, disabled" } })*@
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(m => m.nombre, htmlAttributes: new { @class = "col-sm-3 col-form-label text-left" })
        <div class="col-sm-9">
            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group row">
        @Html.LabelFor(m => m.primerApellido, htmlAttributes: new { @class = "col-sm-3 col-form-label text-left" })
        <div class="col-sm-9">
            @Html.EditorFor(model => model.primerApellido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.primerApellido, "", new { @class = "text-danger" })


        </div>
    </div>
    <div class="form-group row">
        @Html.Label("Segundo Apellido", htmlAttributes: new { @class = "col-sm-3 col-form-label text-right" })
        <div class="col-sm-9">
            @Html.EditorFor(model => model.segundoApellido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.segundoApellido, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group row">
        @Html.Label("Fecha de Nacimiento", htmlAttributes: new { @class = "col-sm-3 col-form-label text-right" })
        <div class="col-sm-9">
            @Html.EditorFor(model => model.fechaNacimiento, new { htmlAttributes = new { @class = "form-control"} })
            @Html.ValidationMessageFor(model => model.fechaNacimiento, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group row">
        @Html.Label("CURP", htmlAttributes: new { @class = "col-sm-3 col-form-label text-right" })
        <div class="col-sm-9">
            @Html.EditorFor(model => model.curp, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.curp, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group row">
        @Html.Label("Correo", htmlAttributes: new { @class = "col-sm-3 col-form-label text-right" })
        <div class="col-sm-9">
            @Html.EditorFor(model => model.correo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.correo, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group row">
        @Html.Label("Telefono", htmlAttributes: new { @class = "col-sm-3 col-form-label text-right" })
        <div class="col-sm-9">
            @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group row">
        @Html.Label("Sueldo", htmlAttributes: new { @class = "col-sm-3 col-form-label text-right" })
        <div class="col-sm-9">
            @Html.EditorFor(model => model.sueldo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.sueldo, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group row">
        @Html.Label("Estado", htmlAttributes: new { @class = "col-sm-3 col-form-label text-right" })
        <div class="col-sm-9">
            @Html.DropDownList("idEstadoOrigen", (SelectList)ViewBag.idEstado, htmlAttributes: new { @class = "form-control" })
            @*@Html.EditorFor(model => model.idEstadoOrigen, new { htmlAttributes = new { @class = "col-sm-3 col-form-label text-right" } })*@
        </div>
    </div>
    <div class="form-group row">
        @Html.Label("Estatus", htmlAttributes: new { @class = "col-sm-3 col-form-label text-right" })
        <div class="col-sm-9">

            @Html.DropDownList("idEstatus", (SelectList)ViewBag.idEstatus, htmlAttributes: new { @class = "form-control" })



            @*@Html.EditorFor(model => model.idEstadoOrigen, new { htmlAttributes = new { @class = "col-sm-3 col-form-label text-right" } })*@
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-12 text-start">
            <br />
            <input type="Submit" value="Guardar" class="btn btn-primary" />
        </div>
    </div>
}
<br />
@Html.ActionLink("Regresar al Index", "Regresar", "Alumnos", htmlAttributes: new { @class = "btn btn-grey btn-sm" })

4.-MVC/MVCEF3Capas/Presentacion/Views/EstatusAlumnos/Delete.cshtml
@model Entidades.EstatusAlumnos

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EstatusAlumnos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Clave)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Clave)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

4.-MVC/MVCEF3Capas/Presentacion/Views/EstatusAlumnos/Index.cshtml
@model IEnumerable<Entidades.EstatusAlumnos>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Crear", "Create", "Alumnos", htmlAttributes: new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Clave)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Clave)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.ActionLink("Detalles", "Details", new { id = item.id }, htmlAttributes: new { @class = "btn btn-warning btn-sm" })

                @Html.ActionLink("Editar", "Edit", "EstatusAlumnos", new { id = item.id }, htmlAttributes: new { @class = "btn btn-success btn-sm" })

                @Html.ActionLink("Eliminar", "Delete", "EstatusAlumnos", new { id = item.id }, htmlAttributes: new { @class = "btn btn-danger btn-sm" })

                <input id="btnEliminarAJAX" type="button" value="Eliminar - AJAX" class="btn btn-outline-danger btn-sm" onclick="IniAJAX(@item.id)" />

            </td>
        </tr>
    }

</table>


<!-- Modal -->
<div class="modal fade" id="ModalIndex" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabelIndex"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div id="BodyofBody">


               
            

            </div>
        </div>
    </div>
</div>




<script type="text/javascript">

    const urlWebAPI = '@System.Configuration.ConfigurationManager.AppSettings["urlWebAPI"]';

    function IniAJAX(id) {

        $('exampleModalLabelIndex').text("TI Capital Humano");
        let url = urlWebAPI + "/" + id
        //console.log(url);
        AjaxGETEstatusAlumno(url, MostrarModalEstatus);
    }

    function EliminarAJAX(id) {
        let url = urlWebAPI + "/" + id
        //console.log(url);
        AjaxDELETEEstatusAlumno(url, CerrarM);
    }

    function CerrarM(DataEstatusJSON) {
        location.reload();
    }

    function MostrarModalEstatus(DataEstatusJSON) {

        const template = `

        <div class="modal-body">
                    <table class="table">
               <tr>
                   <th>
                       ID
                   </th>
                   <th>
                       Clave
                   </th>
                   <th>
                       Nombre
                   </th>
                   <th>
               </tr>
               <tr>
                   <td>
                       ${DataEstatusJSON.id}
                   </td>
                   <td>
                      ${DataEstatusJSON.clave}
                   </td>
                   <td>
                       ${DataEstatusJSON.nombre}
                   </td>
               </tr>
           </table>
        </div>
           <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal" onclick="EliminarAJAX(${DataEstatusJSON.id})">Eliminar</button>
        </div>
             
     
        `;

       // console.log(template);
        $('#BodyofBody').html(template);
        $('#ModalIndex').modal('show');
    }


</script>